import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/provider/UserProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} container mx-auto px-2 md:px-5 lg:px-10 bg-[#0f0a1a] antialiased dark`}
      >
        <div className="min-h-screen bg-[#0f0a1a] flex">
          {/* <Sidebar /> */}
          <div className="flex-1 overflow-auto">
            <Providers>
              <Toaster richColors position="top-center" />
              <div className="p-6">{children}</div>
            </Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
